Improve typings for event emitters
versatica/mediasoup-client pull request #200
Opened 2022-02-23 18:40 UTC by unao

As a logical continuation of https://github.com/versatica/mediasoup/pull/764 would like to add analogous types for mediasoup client.

I introduced some _implicit_ assumption around `safeEmitAsPromise`: if corresponding type is not specified it allows to pass any arguments otherwise it must be a single argument conforming to the first declared type.

There is still some room left for improvements around `AppData` (for preventing unsafe cast) - if you were interested I could add it once this is merged in.

2022-02-24 10:43 UTC, jmillan approved these changes
:+1:

2022-04-11 09:13 UTC, unao commented
@jmillan @ibc I resolved some conflicts in generated types. Any chance to merge this in?

2022-04-13 13:24 UTC, ibc commented
Will review soon, sorry for the delay.

2022-05-20 09:25 UTC, unao commented
@ibc sure no hurry ;) 
btw. I resolved some other conflicts that popped up since then

2022-05-25 16:40 UTC, ibc commented
We don't forget about this. It's just that we are too busy.

2022-06-13 09:52 UTC, unao commented
I probably will close this PR soon and just fork this repo to move forward.

2022-06-13 09:56 UTC, ibc commented
Please don't. Will manage this PR this week. Promise.

2022-06-18 16:45 UTC, ibc requested changes

2022-06-18 16:45 UTC, ibc commented on src/Transport.ts
> +export type TransportProduceParameters<AppData = unknown> =
`AppData` default value should not be `unkown` but `Record<string, unknown>` (everywhere).

2022-06-18 20:48 UTC, ibc commented
@unao I've made some changes that improve `EnhancedEventEmitter` and I assume we should use the same in mediasoup-client:

https://github.com/versatica/mediasoup/pull/836

2022-07-01 13:23 UTC, ibc commented
Closed in favour of https://github.com/versatica/mediasoup-client/pull/209

2022-07-01 13:23 UTC, closed without merging