fix: Improve batching behaviour with parallel calls to consume()
versatica/mediasoup-client pull request #243
Opened 2023-02-02 19:42 UTC by t-mullen

When creating multiple consumers in parallel like this:
```
await Promise.all([
  transport.consume(/* ... */), 
  transport.consume(/* ... */), 
  // ...
])
```
The awaitQueue will push a consumer creation task with the first consumer, then another with all the other consumers. This inefficient batching slows down consumer creation.

To improve this, this PR waits for any existing microtasks to finish before creating the first task. This results in at most one task pushed to the awaitQueue for any calls to consume() still in the microtask queue. The same optimization was applied to pausing/resuming consumers.

2023-02-03 11:56 UTC, ibc commented
Makes sense. Thanks. Will entirely review it on next week.

2023-02-03 13:53 UTC, jmillan approved these changes
Nice :-)

2023-02-04 12:05 UTC, ibc requested changes

2023-02-04 12:05 UTC, ibc commented on src/Transport.ts
> +				if (this._consumerResumeInProgress === false)
Here, at the top of the callback, we must check this._closed` and `throw new InvalidStateError('closed');` if closed.

2023-02-04 12:05 UTC, ibc commented on src/tests/test.ts
> +	]);
cosmetic

```suggestion

	const allConsumersCreated = Promise.all(
		[
			waitForConsumer(videoConsumerRemoteParameters1.id),
			waitForConsumer(videoConsumerRemoteParameters2.id)
		]);
```

2023-02-06 09:11 UTC, ibc commented
This maybe unrelated to this PR:

We are not checking `this._closed` flag in `Transport.ts` when it comes to process enqueued tasks. Let me do this.

2023-02-06 16:07 UTC, ibc requested changes

2023-02-06 16:07 UTC, ibc commented on src/Transport.ts
> +				if (this._consumerResumeInProgress === false)
This should be done in all usages of `queueMicrotask()`, not just in this one.

2023-02-06 16:10 UTC, ibc commented
CI is failing: Please run `npm run lint`

2023-02-06 16:10 UTC, ibc commented
I will merge and fix locally.

2023-02-06 16:11 UTC, merged

2023-02-06 16:21 UTC, ibc commented
Released in 3.6.76. Thanks.